#!/usr/bin/env python3
"""Keyword-file input for campaign-builder v2 create mode — pure parsing, no I/O beyond
reading the workbook.

Parses a keyword-research workbook into the same campaigns[] shape the config contract
uses (config.TEMPLATE.json), so create mode can build campaigns straight from keyword
research instead of (or in addition to) a hand-written config. Wired into build_campaigns
.py via `--keyword-file` / `--keyword-sheet`.

Two supported shapes, tried in this order:

  1. **EW SEO keyword workbook's "5. Campaign Structure" tab** (see
     tools/amazon-seo-keyword-workbook/fill_campaign_structure.py, which scaffolds/fills
     this same tab as a VISUAL plan). Bucketed sections — Rank-SKW, Shield-SKW,
     Long-Tails (Halo), Discovery-Root Keywords, Shield Discovery-Brand Keywords,
     PAT (Stronger)/(Weaker) — each with a Keyword/Search Volume (or ASINs/Brand) column
     pair, a Sum row terminator. This module scans those sections independently (it does
     NOT import the sibling tool, to keep this toolkit usable standalone) — if that tool's
     scaffold titles change, `SECTION_ANCHORS` below needs a matching update.

     NOTE: this reads the bucket *data columns* (whatever was filled in, by hand or by
     fill_campaign_structure.py --apply), not the tab's "Proposed Campaign Names" block —
     naming is generated by this toolkit's own naming module, not copied from the workbook.

  2. **Generic tolerant flat table** fallback: any worksheet with tolerant header
     matching for columns naming a campaign type, keyword(s), product, match type, and
     bid. One row = one keyword; rows sharing (campaign_type, product) group into a
     single campaign spec, in row order.

UNVALIDATED against a real EW keyword workbook — built against the documented
"5. Campaign Structure" scaffold shape (fill_campaign_structure.py's SECTION_ANCHORS) and
a synthetic fixture (see the test run in README.md). Validate against a real client
workbook before relying on this in production; if the real scaffold differs, the section
scan degrades to "no sections found" -> falls back to the generic flat parser rather than
silently miscounting.
"""
from __future__ import annotations

import re

CAMPAIGN_STRUCTURE_TAB = "5. Campaign Structure"

# (campaign_type, campaign_purpose, kind, default_descriptor). "__discovery__" is
# resolved to BMM/Phrase by the column label ("BMM" appearing in the label vs not)
# once the section is found. default_descriptor fills target_descriptor when the
# sheet has no per-column label above the header (e.g. distinguishing the two PAT
# buckets from each other so they don't collide on the same campaign name).
SECTION_ANCHORS = {
    "rank-skw": ("SKW", "RANK_SKW", "keywords", ""),
    "shield-skw": ("SKW", "SHIELD", "keywords", ""),
    "long-tails (halo)": ("Halo", "HALO", "keywords", ""),
    "discovery-root keywords": ("__discovery__", "DISCOVERY", "keywords", ""),
    "shield discovery-brand keywords": ("__discovery__", "SHIELD", "keywords", ""),
    "pat (stronger)": ("PAT", "DISCOVERY", "asins", "Stronger"),
    "pat (weaker)": ("PAT", "DISCOVERY", "asins", "Weaker"),
}

_PAIR_HEADERS = {"keywords": ("keyword", "search volume"), "asins": ("asins", "brand")}


def _norm(s):
    return re.sub(r"\s+", " ", str(s or "").strip().lower())


def _norm_title(s):
    return re.sub(r"\s*-\s*", "-", _norm(s))


def _grid(ws):
    g = {}
    for row in ws.iter_rows():
        for cell in row:
            if cell.value is not None:
                g[(cell.row, cell.column)] = cell.value
    return g


def scan_campaign_structure_sections(ws):
    """Scan a '5. Campaign Structure'-shaped sheet -> list of
    {campaign_type, campaign_purpose, label, kind, values}. `values` is a list of
    (keyword_or_asin, search_volume_or_brand) pairs. Returns [] if no anchors found
    (caller should fall back to the generic flat parser)."""
    grid = _grid(ws)
    anchors = []  # (row, col, key, campaign_type, purpose, kind, default_descriptor)
    for (r, c), v in grid.items():
        key = _norm_title(v)
        if key in SECTION_ANCHORS:
            ctype, purpose, kind, default_descriptor = SECTION_ANCHORS[key]
            anchors.append((r, c, key, ctype, purpose, kind, default_descriptor))
    if not anchors:
        return []

    by_row = {}
    for a in anchors:
        by_row.setdefault(a[0], []).append(a)

    sections = []
    for row_anchors in by_row.values():
        row_anchors.sort(key=lambda a: a[1])
        for i, (ar, ac, _key, ctype, purpose, kind, default_descriptor) in enumerate(row_anchors):
            col_lo = ac
            col_hi = row_anchors[i + 1][1] - 1 if i + 1 < len(row_anchors) else ws.max_column
            first, second = _PAIR_HEADERS[kind]
            header_row = None
            for hr in range(ar + 1, ar + 4):
                if any(_norm(grid.get((hr, c))) == first for c in range(col_lo, col_hi + 1)):
                    header_row = hr
                    break
            if header_row is None:
                continue
            for c in range(col_lo, col_hi + 1):
                if _norm(grid.get((header_row, c))) != first:
                    continue
                sv_col = next((c2 for c2 in range(c + 1, min(c + 3, col_hi + 1))
                               if _norm(grid.get((header_row, c2))) == second), None)
                if sv_col is None:
                    continue
                label = ""
                for lr in range(header_row - 1, ar, -1):
                    if grid.get((lr, c)) is not None:
                        label = str(grid[(lr, c)]).strip()
                        break
                sum_row = next((sr for sr in range(header_row + 1, header_row + 60)
                                if _norm(grid.get((sr, c))) == "sum"), header_row + 40)
                values = []
                for r in range(header_row + 1, sum_row):
                    kv = grid.get((r, c))
                    if kv is None or not str(kv).strip():
                        continue
                    values.append((str(kv).strip(), grid.get((r, sv_col))))
                if not values:
                    continue
                effective_ctype = ctype
                if ctype == "__discovery__":
                    effective_ctype = "BMM" if "bmm" in _norm(label) else "Phrase"
                sections.append({"campaign_type": effective_ctype, "campaign_purpose": purpose,
                                 "label": label or default_descriptor, "kind": kind, "values": values})
    return sections


def sections_to_campaign_specs(sections, *, product_name="", sku=None, asin=None):
    """Bucketed sections -> campaigns[] spec dicts (config.TEMPLATE.json shape)."""
    specs = []
    for s in sections:
        base = {
            "campaign_type": s["campaign_type"],
            "campaign_purpose": s["campaign_purpose"],
            "product_name": product_name,
            "sku": list(sku or []),
            "asin": list(asin or []),
        }
        if s["kind"] == "asins":
            specs.append({**base, "target_asins": [v[0].upper() for v in s["values"]],
                         "target_descriptor": s["label"]})
        elif s["campaign_type"] == "SKW":
            for kw, _sv in s["values"]:
                specs.append({**base, "keywords": [kw], "target_descriptor": kw})
        elif s["campaign_type"] == "Halo":
            specs.append({**base, "keywords": [kw for kw, _sv in s["values"]],
                         "target_descriptor": s["label"]})
        else:  # BMM / Phrase discovery — one root keyword per campaign
            for kw, _sv in s["values"]:
                specs.append({**base, "keywords": [kw], "target_descriptor": kw,
                             "bmm_modifier": s["campaign_type"] == "BMM"})
    return specs


# --------------------------------------------------------------- generic tolerant fallback
_TYPE_ALIASES = {"skw": "SKW", "single keyword": "SKW", "halo": "Halo", "bmm": "BMM",
                 "broad match modifier": "BMM", "phrase": "Phrase", "auto": "Auto",
                 "pat": "PAT", "product targeting": "PAT"}


def parse_flat_table(ws):
    """Any worksheet with tolerant headers for campaign type / keyword / product / match
    type / bid -> campaigns[] spec dicts, one per (campaign_type, product) group."""
    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        return []
    hdr = [_norm(h) for h in rows[0]]

    def col(*names):
        return next((i for i, h in enumerate(hdr) if h in names), None)

    ci_type = col("campaign type", "campaign_type", "type")
    ci_kw = col("keyword", "keywords", "search term", "search terms")
    ci_prod = col("product", "product_name", "product name", "sku", "asin")
    ci_match = col("match type", "match_type", "match")
    ci_bid = col("bid", "keyword bid", "suggested bid")
    if ci_type is None or ci_kw is None:
        return []

    groups, order = {}, []
    for row in rows[1:]:
        if ci_type >= len(row) or not _norm(row[ci_type]):
            continue
        ctype = _TYPE_ALIASES.get(_norm(row[ci_type]))
        if ctype is None:
            continue
        kw = str(row[ci_kw]).strip() if ci_kw < len(row) and row[ci_kw] else ""
        if not kw:
            continue
        product = (str(row[ci_prod]).strip() if ci_prod is not None
                   and ci_prod < len(row) and row[ci_prod] else "")
        match_type = (str(row[ci_match]).strip().upper() if ci_match is not None
                      and ci_match < len(row) and row[ci_match] else "")
        bid = None
        if ci_bid is not None and ci_bid < len(row) and row[ci_bid] not in (None, ""):
            m = re.search(r"[\d.]+", str(row[ci_bid]))
            bid = float(m.group()) if m else None
        key = (ctype, product)
        if key not in groups:
            groups[key] = {"campaign_type": ctype, "product_name": product, "keywords": [],
                           "match_type": match_type, "keyword_bid": bid, "target_descriptor": product}
            order.append(key)
        groups[key]["keywords"].append(kw)
    return [groups[k] for k in order]


def parse_keyword_workbook(path, *, sheet=None, product_name="", sku=None, asin=None):
    """Top-level entry point. Returns a list of campaigns[]-shaped spec dicts."""
    import openpyxl
    wb = openpyxl.load_workbook(path, data_only=True)
    if sheet and sheet in wb.sheetnames:
        specs = parse_flat_table(wb[sheet])
        if specs:
            return specs
    if CAMPAIGN_STRUCTURE_TAB in wb.sheetnames:
        sections = scan_campaign_structure_sections(wb[CAMPAIGN_STRUCTURE_TAB])
        if sections:
            return sections_to_campaign_specs(sections, product_name=product_name, sku=sku, asin=asin)
    target = wb[sheet] if sheet and sheet in wb.sheetnames else wb[wb.sheetnames[0]]
    return parse_flat_table(target)
