#!/usr/bin/env python3
"""Rebuild the knowledge denylist from the team vault and the Grimoire config.

Writes `_local/knowledge-redaction-terms.txt` (gitignored) with two sections:

- `# generated`: rebuilt on every run from the vault client folders, each
  hub's `slug:`, each `Amazon Ops.md` JSON block (seller_central_name,
  amazon_ads_ppc_name, profile_name, main_stakeholders, website) and the
  client entries of the Grimoire config.
- `# manual additions`: kept as is across runs. When the terms file does not
  exist yet, it is seeded from `_local/knowledge-redaction-manual-seed.txt`
  (one term per line, gitignored) when that file exists.

Names never live in this tracked file. Stdlib only.

Usage: python3 tools/knowledge/seed_redaction_terms.py [--vault DIR]
       [--config FILE] [--out FILE] [--manual-seed FILE]
Prints the generated and manual term counts, never the terms.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from urllib.parse import urlparse

WORKSPACE_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(WORKSPACE_ROOT / "tools"))

from ads_recall import resolve_vault  # noqa: E402

DEFAULT_OUT = WORKSPACE_ROOT / "_local" / "knowledge-redaction-terms.txt"
DEFAULT_MANUAL_SEED = WORKSPACE_ROOT / "_local" / "knowledge-redaction-manual-seed.txt"
# The Grimoire checkout sits next to this repo. WIZARDS_AI_CONFIG overrides.
DEFAULT_GRIMOIRE_CONFIG = WORKSPACE_ROOT.parent / "wizards-ai" / "config.json"

HEADER = "# generated by tools/knowledge/seed_redaction_terms.py, do not commit"
GENERATED_MARK = "# generated"
MANUAL_MARK = "# manual additions"

MIN_LEN = 3
GENERIC_WORDS = {
    "amazon",
    "brand",
    "store",
    "null",
    "none",
    "n/a",
    "tbd",
    "unknown",
    "stores",
    "shop",
    "page",
    "www",
}
OPS_NAME_KEYS = ("seller_central_name", "amazon_ads_ppc_name", "profile_name")
STAKEHOLDER_KEY = "main_stakeholders"
WEBSITE_KEY = "website"
# A trailing marketplace code on a profile name ("Name US") is not part of the name.
# The same goes for a slug suffix ("name-us").
MARKETPLACE_SUFFIX = re.compile(
    r"[\s-]+(?:US|USA|CA|MX|DE|UK|GB|FR|IT|ES|NL|SE|PL|AU|AUS|JP|EU|BE|IE|TR|AE|SA|IN|BR|SG)$",
    re.IGNORECASE,
)
LEGAL_SUFFIX = re.compile(r"\s+(?:GmbH|UG|AG|KG|LLC|Ltd\.?|Inc\.?|Co\.?|SRL|S\.r\.l\.|BV|AB|Pty)$", re.I)
# In the Grimoire config, string values under these keys of a client entry are names.
GRIMOIRE_NAME_KEYS = {
    "name",
    "slug",
    "client_name",
    "client_slug",
    "client_aliases",
    "aliases",
    "alias",
    "brand",
    "brand_name",
    "brands",
    "account",
    "client_folder",
    "channel",
    "channel_name",
    "seller_central_name",
}


def _clean(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip().strip(".,;:")


def keep_term(value: object) -> str | None:
    """Return the cleaned term, or None for values that make poor terms."""
    if not isinstance(value, str):
        return None
    term = _clean(value)
    if len(term) < MIN_LEN:
        return None
    if term.casefold() in GENERIC_WORDS:
        return None
    if re.fullmatch(r"[\d\s.,:/-]+", term):
        return None
    if term.lower().startswith(("http://", "https://")):
        return None
    return term


def _strip_parens(text: str) -> str:
    previous = None
    while previous != text:
        previous = text
        text = re.sub(r"\([^()]*\)", " ", text)
    return text


def name_variants(value: str) -> list[str]:
    """A name, plus the name without a marketplace code or legal suffix."""
    base = _clean(_strip_parens(value))
    out = [base]
    for regex in (MARKETPLACE_SUFFIX, LEGAL_SUFFIX):
        trimmed = regex.sub("", base).strip()
        if trimmed and trimmed not in out:
            out.append(trimmed)
    return out


def split_people(value: str) -> list[str]:
    """Split a stakeholder line into name-like chunks.

    Splits on commas, semicolons, sentence stops, `&`, `/` and ` and `; drops
    parenthetical roles and a `Role:` prefix; keeps chunks of one to four
    capitalised words, which leaves prose out.
    """
    text = _strip_parens(value)
    chunks = re.split(r"[,;/&]|\.\s|\.$|\s+and\s+|\s+und\s+", text)
    names: list[str] = []
    for chunk in chunks:
        if ":" in chunk:
            chunk = chunk.split(":", 1)[1]
        chunk = _clean(chunk)
        words = chunk.split()
        if not 1 <= len(words) <= 4:
            continue
        if all(w[:1].isupper() for w in words):
            names.append(chunk)
    return names


def website_terms(value: str) -> list[str]:
    """Host without www, its leading label, and store slugs on Amazon hosts."""
    raw = value.strip()
    if not raw or raw.casefold() in GENERIC_WORDS:
        return []
    parsed = urlparse(raw if "://" in raw else f"https://{raw}")
    host = (parsed.hostname or "").lower()
    if host.startswith("www."):
        host = host[4:]
    if not host or "." not in host:
        return []
    labels = host.split(".")
    if "amazon" in labels:
        segments = [s for s in parsed.path.split("/") if s]
        return [s for s in segments if not re.search(r"\d", s)]
    return [host, labels[0]]


def _frontmatter_slug(path: Path) -> str | None:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    for line in lines[1:]:
        if line.strip() == "---":
            break
        m = re.match(r"^slug:\s*(.*)$", line)
        if m:
            return m.group(1).strip().strip("\"'")
    return None


def _json_blocks(text: str) -> list[object]:
    blocks: list[object] = []
    for m in re.finditer(r"```json\s*\n(.*?)```", text, re.S):
        try:
            blocks.append(json.loads(m.group(1)))
        except json.JSONDecodeError:
            continue
    return blocks


def _walk_ops(node: object, out: list[str]) -> None:
    """Collect the named Amazon Ops fields wherever they sit in the JSON."""
    if isinstance(node, dict):
        for key, value in node.items():
            if isinstance(value, str):
                if key in OPS_NAME_KEYS:
                    out.extend(name_variants(value))
                elif key == STAKEHOLDER_KEY:
                    out.extend(split_people(value))
                elif key == WEBSITE_KEY:
                    out.extend(website_terms(value))
            elif isinstance(value, list) and key == STAKEHOLDER_KEY:
                for item in value:
                    if isinstance(item, str):
                        out.extend(split_people(item))
            else:
                _walk_ops(value, out)
    elif isinstance(node, list):
        for item in node:
            _walk_ops(item, out)


def vault_terms(vault: Path) -> list[str]:
    clients = vault / "Clients"
    raw: list[str] = []
    if not clients.is_dir():
        return raw
    for folder in sorted(p for p in clients.iterdir() if p.is_dir()):
        if folder.name.startswith("_") or folder.name.startswith("."):
            continue
        raw.append(folder.name)
        hub = folder / f"{folder.name}.md"
        if hub.is_file():
            slug = _frontmatter_slug(hub)
            if slug:
                raw.append(slug)
        ops = folder / "Amazon Ops.md"
        if ops.is_file():
            try:
                text = ops.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            for block in _json_blocks(text):
                _walk_ops(block, raw)
    return raw


def _is_entry_map(value: object) -> bool:
    """A non-empty dict whose values are all entries (dicts or lists), not settings."""
    return (
        isinstance(value, dict)
        and bool(value)
        and all(isinstance(v, (dict, list)) for v in value.values())
    )


def _collect_client_strings(node: object, out: list[str], in_client: bool) -> None:
    """Walk the Grimoire config. Inside any key that mentions `client`, take
    string values of name-like keys and the keys of name-keyed maps."""
    if isinstance(node, dict):
        for key, value in node.items():
            key_l = str(key).lower()
            client_scope = in_client or "client" in key_l
            if client_scope and isinstance(value, str) and key_l in GRIMOIRE_NAME_KEYS:
                out.append(value)
            elif client_scope and isinstance(value, list) and key_l in GRIMOIRE_NAME_KEYS:
                out.extend(v for v in value if isinstance(v, str))
            else:
                if "client" in key_l and _is_entry_map(value):
                    # Maps keyed by client name or slug, such as client_accounts.
                    out.extend(value)
                _collect_client_strings(value, out, client_scope)
    elif isinstance(node, list):
        for item in node:
            _collect_client_strings(item, out, in_client)


def grimoire_terms(config_path: Path) -> list[str]:
    if not config_path.is_file():
        return []
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        print(f"seed_redaction_terms: cannot read Grimoire config: {exc}", file=sys.stderr)
        return []
    raw: list[str] = []
    _collect_client_strings(data, raw, False)
    out: list[str] = []
    for value in raw:
        out.extend(name_variants(value))
    return out


def dedupe(values: list[str]) -> list[str]:
    seen: dict[str, str] = {}
    for value in values:
        term = keep_term(value)
        if term is None:
            continue
        seen.setdefault(term.casefold(), term)
    return sorted(seen.values(), key=str.casefold)


def read_manual_section(path: Path) -> list[str] | None:
    """Return the lines after `# manual additions`, or None when the file is missing."""
    if not path.is_file():
        return None
    lines = path.read_text(encoding="utf-8").splitlines()
    for idx, line in enumerate(lines):
        if line.strip() == MANUAL_MARK:
            manual = lines[idx + 1 :]
            while manual and not manual[-1].strip():
                manual.pop()
            return manual
    return []


def render(generated: list[str], manual: list[str]) -> str:
    lines = [HEADER, "", GENERATED_MARK, *generated, "", MANUAL_MARK, *manual]
    return "\n".join(lines) + "\n"


def count_terms(lines: list[str]) -> int:
    return sum(1 for line in lines if line.strip() and not line.strip().startswith("#"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Rebuild the knowledge redaction denylist.")
    parser.add_argument("--vault", help="team vault path (default: resolve like tools/ads_recall.py)")
    parser.add_argument("--config", help="Grimoire config.json (default: ../wizards-ai/config.json)")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="terms file to write")
    parser.add_argument("--manual-seed", default=str(DEFAULT_MANUAL_SEED), help="first-run manual terms")
    args = parser.parse_args(argv)

    vault = resolve_vault(args.vault)
    if vault is None:
        print("seed_redaction_terms: team vault not found, vault terms skipped", file=sys.stderr)
    config_path = Path(args.config or os.environ.get("WIZARDS_AI_CONFIG") or DEFAULT_GRIMOIRE_CONFIG)
    if not config_path.is_file():
        print("seed_redaction_terms: Grimoire config not found, config terms skipped", file=sys.stderr)

    raw = (vault_terms(vault) if vault else []) + grimoire_terms(config_path)
    generated = dedupe(raw)

    out = Path(args.out)
    manual = read_manual_section(out)
    if manual is None:
        seed = Path(args.manual_seed)
        manual = []
        if seed.is_file():
            manual = [
                line.strip()
                for line in seed.read_text(encoding="utf-8").splitlines()
                if line.strip() and not line.strip().startswith("#")
            ]
        else:
            print("seed_redaction_terms: no manual seed file, manual section starts empty", file=sys.stderr)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(generated, manual), encoding="utf-8")
    print(f"generated terms: {len(generated)}")
    print(f"manual terms: {count_terms(manual)}")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
